# Generated by Django 4.0.4 on 2022-06-22 09:22

from django.db import migrations, models
import mainApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.ImageField(blank=True, upload_to=mainApp.models.upload_to_func)),
            ],
        ),
    ]
