# Generated by Django 4.0.4 on 2022-07-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilemodel',
            name='folder_name',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
