# Generated by Django 4.0.4 on 2022-07-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_folder_imgupload_delete_uploadfilemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgupload',
            name='folder',
        ),
        migrations.AddField(
            model_name='imgupload',
            name='folder_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
